-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2024-02-02 19:38:43.546

-- tables
-- Table: CARGO
CREATE TABLE CARGO (
    ID bigserial  NOT NULL,
    DESCRICAO varchar(200)  NOT NULL,
    TIPO_CARGO varchar(100)  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    CLASSE_ID bigserial  NOT NULL,
    PADRAO_ID bigserial  NOT NULL,
    CONSTRAINT TIPO_CARGO_TYPE_CHECK CHECK (TIPO_CARGO IN ('CARGO_COMISSAO','CARGO_EFETIVO','CARGO_PUBLICO')) NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT CARGO_pk PRIMARY KEY (ID)
);

-- Table: CLASSE
CREATE TABLE CLASSE (
    ID bigserial  NOT NULL,
    DESCRICAO varchar(50)  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    CONSTRAINT CLASSE_pk PRIMARY KEY (ID)
);

-- Table: CLIENTE
CREATE TABLE CLIENTE (
    id bigserial  NOT NULL,
    data_inicio timestamp  NOT NULL,
    data_fim timestamp  NOT NULL,
    tipo_cliente_id bigserial  NOT NULL,
    CONSTRAINT CLIENTE_pk PRIMARY KEY (id)
);

-- Table: CLIENTE_CONTA
CREATE TABLE CLIENTE_CONTA (
    id bigserial  NOT NULL,
    cliente_id bigserial  NOT NULL,
    conta_id bigserial  NOT NULL,
    data_inicio timestamp  NOT NULL,
    data_fim timestamp  NOT NULL,
    CONSTRAINT CLIENTE_CONTA_pk PRIMARY KEY (id)
);

-- Table: CONTA
CREATE TABLE CONTA (
    id bigserial  NOT NULL,
    data_inicio timestamp  NOT NULL,
    data_fim timestamp  NOT NULL,
    saldo decimal(16,2)  NOT NULL,
    CONSTRAINT id PRIMARY KEY (id)
);

-- Table: CONTATO
CREATE TABLE CONTATO (
    id bigserial  NOT NULL,
    data_inicio date  NOT NULL,
    data_fim date  NULL,
    pessoa_id bigserial  NOT NULL,
    CONSTRAINT CONTATO_pk PRIMARY KEY (id)
);

-- Table: CONTA_TIPO_CONTA
CREATE TABLE CONTA_TIPO_CONTA (
    data_inicio date  NOT NULL,
    data_fim date  NOT NULL,
    CONTA_id bigserial  NOT NULL,
    TIPO_CONTA_id bigserial  NOT NULL,
    id bigserial  NOT NULL,
    CONSTRAINT CONTA_TIPO_CONTA_pk PRIMARY KEY (id)
);

-- Table: DOCUMENTOS
CREATE TABLE DOCUMENTOS (
    ID bigserial  NOT NULL,
    CHAVE varchar(50)  NOT NULL,
    PESSOA_FISICA_ID bigserial  NOT NULL,
    NOME varchar(200)  NOT NULL,
    CONSTRAINT DOCUMENTOS_pk PRIMARY KEY (ID)
);

-- Table: EMAIL
CREATE TABLE EMAIL (
    ID bigserial  NOT NULL,
    EMAIL varchar(100)  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    CONTATO_ID bigserial  NOT NULL,
    CONSTRAINT EMAIL_pk PRIMARY KEY (ID)
);

CREATE INDEX IDX_EMAIL on EMAIL (EMAIL ASC);

-- Table: ENDERECO
CREATE TABLE ENDERECO (
    ID bigserial  NOT NULL,
    CEP varchar(8)  NOT NULL,
    TIPO_LOGRADOURO_ID bigserial  NOT NULL,
    LOGRADOURO varchar(100)  NULL,
    COMPLEMENTO varchar(100)  NULL,
    BAIRRO varchar(150)  NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    MUNICIPIO_ID bigserial  NOT NULL,
    CONTATO_ID bigserial  NOT NULL,
    CONSTRAINT ENDERECO_pk PRIMARY KEY (ID)
);

CREATE INDEX IDX_ENDERECO_LOGRADOURO on ENDERECO (LOGRADOURO ASC);

-- Table: FLUXO_APROVAÇÃO
CREATE TABLE portal.FLUXO_APROVAÇÃO (
    column_1 bigserial  NOT NULL,
    CONSTRAINT FLUXO_APROVAÇÃO_pk PRIMARY KEY (column_1)
);

-- Table: GRUPO
CREATE TABLE GRUPO (
    ID bigserial  NOT NULL,
    NOME varchar(200)  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    PERFIL_ID bigserial  NULL,
    CONSTRAINT GRUPO_pk PRIMARY KEY (ID)
);

CREATE INDEX IDX_GRUPO_NOME on GRUPO (NOME ASC);

-- Table: ITEM
CREATE TABLE ITEM (
    ID bigserial  NOT NULL,
    NOME varchar(200)  NOT NULL,
    DESCRICAO varchar(200)  NULL,
    URL varchar(255)  NOT NULL,
    POSICAO int  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    MENU_ID bigserial  NOT NULL,
    CONSTRAINT ITEM_pk PRIMARY KEY (ID)
);

CREATE INDEX IDX_ITEM_NOME on ITEM (NOME ASC);

CREATE INDEX IDX_ITEM_DESCRICAO on ITEM (DESCRICAO ASC);

-- Table: LIMITE_TRANSACIONAIS
CREATE TABLE portal.LIMITE_TRANSACIONAIS (
    column_1 bigserial  NOT NULL,
    CONSTRAINT LIMITE_TRANSACIONAIS_pk PRIMARY KEY (column_1)
);

-- Table: MENU
CREATE TABLE MENU (
    ID integer  NOT NULL,
    DESCRICAO varchar2(200)  NOT NULL,
    POSICAO integer  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    MENU_ID integer  NULL,
    MODULO_ID integer  NOT NULL,
    CONSTRAINT MENU_pk PRIMARY KEY (ID)
);

CREATE INDEX IDX_MENU_DESCRICAO on MENU (DESCRICAO ASC);

-- Table: MODULO
CREATE TABLE MODULO (
    ID bigserial  NOT NULL,
    DESCRICAO varchar(255)  NOT NULL,
    MENSAGEM varchar(100)  NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    SISTEMA_ID bigserial  NOT NULL,
    CONSTRAINT MODULO_pk PRIMARY KEY (ID)
);

CREATE INDEX IDX_MODULO_DESCRICAO on MODULO (DESCRICAO ASC);

-- Table: MUNICIPIO
CREATE TABLE MUNICIPIO (
    ID bigserial  NOT NULL,
    CODIGO_IBGE int  NOT NULL,
    NOME varchar(200)  NOT NULL,
    UF varchar(2)  NOT NULL,
    DESCENTRALIZADO char(1)  NOT NULL,
    CONSTRAINT MUNICIPIO_pk PRIMARY KEY (ID)
);

CREATE INDEX IDX_MUNICIPIO_NOME on MUNICIPIO (NOME ASC);

-- Table: PADRAO
CREATE TABLE PADRAO (
    ID bigserial  NOT NULL,
    DESCRICAO varchar(100)  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    CONSTRAINT PADRAO_pk PRIMARY KEY (ID)
);

-- Table: PAIS
CREATE TABLE PAIS (
    ID bigserial  NOT NULL,
    NOME varchar(200)  NOT NULL,
    NACIONALIDADE varchar(200)  NOT NULL,
    CONSTRAINT PAIS_pk PRIMARY KEY (ID)
);

-- Table: PAPEL
CREATE TABLE PAPEL (
    ID bigserial  NOT NULL,
    NOME varchar(200)  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    PAPEL_ID bigserial  NOT NULL,
    CONSTRAINT PAPEL_pk PRIMARY KEY (ID)
);

-- Table: PERFIL
CREATE TABLE PERFIL (
    ID bigserial  NOT NULL,
    DESCRICAO varchar(200)  NOT NULL,
    DELEGAVEL int  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    CONSTRAINT delegavel_type_check CHECK (DELEGAVEL IN (1,2)) NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT PERFIL_pk PRIMARY KEY (ID)
);

CREATE INDEX IDX_PERFIL_DESCRICAO on PERFIL (DESCRICAO ASC);

-- Table: PERFIL_ITEM
CREATE TABLE PERFIL_ITEM (
    ID bigserial  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    PERFIL_ID bigserial  NOT NULL,
    ITEM_ID bigserial  NOT NULL,
    CONSTRAINT PERFIL_ITEM_pk PRIMARY KEY (ID)
);

-- Table: PERMISSAO_ITEM
CREATE TABLE PERMISSAO_ITEM (
    ID bigserial  NOT NULL,
    OPERACAO int  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    ITEM_ID bigserial  NOT NULL,
    CONSTRAINT PERMISSAO_ITEM_pk PRIMARY KEY (ID)
);

-- Table: PERMISSAO_SERVICO
CREATE TABLE PERMISSAO_SERVICO (
    ID bigserial  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    OPERACAO int  NOT NULL,
    PERFIL_ID bigserial  NOT NULL,
    SERVICO_ID bigserial  NOT NULL,
    CONSTRAINT PERMISSAO_SERVICO_pk PRIMARY KEY (ID)
);

-- Table: PESSOA
CREATE TABLE PESSOA (
    ID bigserial  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NOT NULL,
    CONSTRAINT PESSOA_pk PRIMARY KEY (ID)
);

-- Table: PESSOA_FISICA
CREATE TABLE PESSOA_FISICA (
    ID bigserial  NOT NULL,
    CPF varchar(11)  NOT NULL,
    NOME varchar(200)  NOT NULL,
    NOME_SOCIAL varchar(200)  NULL,
    SOBRENOME varchar(200)  NULL,
    NASCIMENTO date  NULL,
    NATURALIDADE varchar(100)  NULL,
    SEXO char(1)  NULL,
    ESTADO_CIVIL varchar(25)  NULL,
    RG varchar(100)  NULL,
    RG_ORGAO_EMISSOR varchar(100)  NULL,
    RG_UF_EMITENTE char(2)  NOT NULL,
    PESSOA_ID bigserial  NOT NULL,
    PAIS_ID bigserial  NOT NULL,
    CARGO_ID bigserial  NULL,
    CONSTRAINT sexo_type_check CHECK (sexo IN ('M','F')) NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT estado_civil_type_check CHECK (ESTADO_CIVIL IN ('SOLTEIRO','CASADO','VIUVO','DIVORCIADO','SEPARADO_JUDICIALMENTE')) NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT PESSOA_FISICA_pk PRIMARY KEY (ID)
);

CREATE INDEX IDX_PF_NOME on PESSOA_FISICA (NOME ASC,NOME_SOCIAL ASC,SOBRENOME ASC);

-- Table: PESSOA_JURIDICA
CREATE TABLE PESSOA_JURIDICA (
    ID bigserial  NOT NULL,
    CNPJ_BASE varchar(8)  NULL,
    CNPJ varchar(14)  NOT NULL,
    RAZAO_SOCIAL varchar(200)  NULL,
    NOME_FANTASIA varchar(200)  NOT NULL,
    PESSOA_ID bigserial  NOT NULL,
    PESSOA_JURIDICA_ID bigserial  NULL,
    NATUREZA_JURIDICA varchar(200)  NULL,
    PORTE_EMPRESA varchar(200)  NULL,
    INSCRICAO_MUNICIPAL varchar(15)  NULL,
    IM_UF char(2)  NULL,
    INSCRICAO_ESTADUAL varchar(200)  NULL,
    IE_UF char(2)  NOT NULL,
    CONSTRAINT PESSOA_JURIDICA_pk PRIMARY KEY (ID)
);

CREATE INDEX IDX_PJ_CNPJ on PESSOA_JURIDICA (CNPJ ASC);

CREATE INDEX IDX_PJ_RAZAO_SOCIAL on PESSOA_JURIDICA (RAZAO_SOCIAL ASC);

CREATE INDEX IDX_PJ_NOME_FANTASIA on PESSOA_JURIDICA (NOME_FANTASIA ASC);

-- Table: PRODUTOS_SERVICOS
CREATE TABLE PRODUTOS_SERVICOS (
    id bigserial  NOT NULL,
    data_inicio date  NOT NULL,
    data_fim date  NOT NULL,
    CONSTRAINT PRODUTOS_SERVICOS_pk PRIMARY KEY (id)
);

-- Table: RESPONSAVEL_SISTEMA
CREATE TABLE RESPONSAVEL_SISTEMA (
    ID bigserial  NOT NULL,
    USUARIO_ID bigserial  NOT NULL,
    SISTEMA_ID bigserial  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    CONSTRAINT RESPONSAVEL_SISTEMA_pk PRIMARY KEY (ID)
);

-- Table: SERVICO
CREATE TABLE SERVICO (
    ID bigserial  NOT NULL,
    DESCRICAO varchar(100)  NOT NULL,
    ROTA varchar(255)  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    SISTEMA_ID bigserial  NOT NULL,
    CONSTRAINT SERVICO_pk PRIMARY KEY (ID)
);

CREATE INDEX IDX_SERVICO_DESCRICAO on SERVICO (DESCRICAO ASC);

-- Table: SISTEMA
CREATE TABLE SISTEMA (
    ID bigserial  NOT NULL,
    NOME varchar(200)  NOT NULL,
    DESCRICAO varchar(200)  NULL,
    URL text  NOT NULL,
    MENSAGEM varchar(200)  NULL,
    URL_LOGOTIPO varchar(255)  NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    CONSTRAINT SISTEMA_pk PRIMARY KEY (ID)
);

CREATE INDEX IDX_SISTEMA_NOME on SISTEMA (NOME ASC);

CREATE INDEX IDX_SISTEMA_DESCRICAO on SISTEMA (DESCRICAO ASC);

-- Table: TELEFONE
CREATE TABLE TELEFONE (
    ID bigserial  NOT NULL,
    DDD varchar(3)  NOT NULL,
    NUMERO varchar(10)  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    CONTATO_ID bigserial  NOT NULL,
    CONSTRAINT TELEFONE_pk PRIMARY KEY (ID)
);

CREATE INDEX IDX_TELEFONE_NUMERO on TELEFONE (NUMERO ASC);

-- Table: TIPO_CLIENTE
CREATE TABLE TIPO_CLIENTE (
    id bigserial  NOT NULL,
    data_inicio timestamp  NOT NULL,
    data_fim timestamp  NOT NULL,
    CONSTRAINT TIPO_CLIENTE_pk PRIMARY KEY (id)
);

-- Table: TIPO_CONTA
CREATE TABLE TIPO_CONTA (
    id bigserial  NOT NULL,
    data_inicio date  NOT NULL,
    data_fim date  NOT NULL,
    CONSTRAINT TIPO_CONTA_pk PRIMARY KEY (id)
);

-- Table: TIPO_LOGRADOURO
CREATE TABLE TIPO_LOGRADOURO (
    ID bigserial  NOT NULL,
    CODIGO varchar(5)  NOT NULL,
    DESCRICAO varchar(200)  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    CONSTRAINT TIPO_LOGRADOURO_pk PRIMARY KEY (ID)
);

CREATE INDEX IDX_TIPO_LOGRADOURO_DESCRICAO on TIPO_LOGRADOURO (DESCRICAO ASC);

-- Table: TIPO_TRANSACOES
CREATE TABLE TIPO_TRANSACOES (
    id bigserial  NOT NULL,
    data_inicio date  NOT NULL,
    data_fim date  NOT NULL,
    CONSTRAINT TIPO_TRANSACOES_pk PRIMARY KEY (id)
);

-- Table: TOKEN
CREATE TABLE TOKEN (
    ID bigserial  NOT NULL,
    TOKEN text  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    DATA_SUSPENSAO date  NULL,
    SISTEMA_ID bigserial  NOT NULL,
    CONSTRAINT status_type_check CHECK (STATUS in ('SUSPENSA','REVOGADA')) NOT DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT TOKEN_pk PRIMARY KEY (ID)
);

-- Table: TRANSACAO
CREATE TABLE TRANSACAO (
    id bigserial  NOT NULL,
    data_inicio date  NOT NULL,
    data_fim date  NOT NULL,
    tipo_transacoes_id bigserial  NOT NULL,
    CONSTRAINT TRANSACAO_pk PRIMARY KEY (id)
);

-- Table: TRANSACAO_CONTA
CREATE TABLE TRANSACAO_CONTA (
    id bigserial  NOT NULL,
    data_inicio date  NOT NULL,
    data_fim date  NOT NULL,
    transacao_id bigserial  NOT NULL,
    conta_id bigserial  NOT NULL,
    valor decimal(16,2)  NOT NULL,
    CONSTRAINT TRANSACAO_CONTA_pk PRIMARY KEY (id)
);

-- Table: USUARIO
CREATE TABLE USUARIO (
    ID bigserial  NOT NULL,
    LOGIN varchar(11)  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    GRUPO_ID bigserial  NULL,
    PERFIL_ID bigserial  NULL,
    ADMIN_PORTAL char(1)  NOT NULL,
    CONSTRAINT USUARIO_pk PRIMARY KEY (ID)
);

CREATE INDEX IDX_USUARIO_LOGIN on USUARIO (LOGIN ASC);

-- Table: USUARIO_CONTA
CREATE TABLE USUARIO_CONTA (
    conta_id bigserial  NOT NULL,
    data_inicio timestamp  NOT NULL,
    data_fim timestamp  NOT NULL,
    usuario_id bigserial  NOT NULL
);

-- Table: VINCULO
CREATE TABLE VINCULO (
    ID bigserial  NOT NULL,
    DATA_INICIO date  NOT NULL,
    DATA_FIM date  NULL,
    PESSOA_ID bigserial  NOT NULL,
    USUARIO_ID bigserial  NOT NULL,
    CONSTRAINT VINCULO_pk PRIMARY KEY (ID)
);

-- Table: VINCULO_PAPEL
CREATE TABLE VINCULO_PAPEL (
    ID bigserial  NOT NULL,
    PAPEL_ID bigserial  NOT NULL,
    VINCULO_ID bigserial  NULL,
    DATA_INICIO date  NULL,
    DATA_FIM date  NULL,
    CONSTRAINT VINCULO_PAPEL_pk PRIMARY KEY (ID)
);

-- Table: VINCULO_TIPO_CONTA_SERVICO
CREATE TABLE VINCULO_TIPO_CONTA_SERVICO (
    id bigserial  NOT NULL,
    data_inicio date  NOT NULL,
    data_fim date  NOT NULL,
    PRODUTOS_SERVICOS_id bigserial  NOT NULL,
    CONTA_TIPO_CONTA_id bigserial  NOT NULL,
    CONSTRAINT VINCULO_TIPO_CONTA_SERVICO_pk PRIMARY KEY (id)
);

-- foreign keys
-- Reference: CARGO_CLASSE (table: CARGO)
ALTER TABLE CARGO ADD CONSTRAINT CARGO_CLASSE
    FOREIGN KEY (CLASSE_ID)
    REFERENCES CLASSE (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: CARGO_PADRAO (table: CARGO)
ALTER TABLE CARGO ADD CONSTRAINT CARGO_PADRAO
    FOREIGN KEY (PADRAO_ID)
    REFERENCES PADRAO (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: CHAVE_ACESSO_SISTEMA (table: TOKEN)
ALTER TABLE TOKEN ADD CONSTRAINT CHAVE_ACESSO_SISTEMA
    FOREIGN KEY (SISTEMA_ID)
    REFERENCES SISTEMA (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: CLIENTE_CONTA_CLIENTE (table: CLIENTE_CONTA)
ALTER TABLE CLIENTE_CONTA ADD CONSTRAINT CLIENTE_CONTA_CLIENTE
    FOREIGN KEY (cliente_id)
    REFERENCES CLIENTE (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: CLIENTE_CONTA_CONTA (table: CLIENTE_CONTA)
ALTER TABLE CLIENTE_CONTA ADD CONSTRAINT CLIENTE_CONTA_CONTA
    FOREIGN KEY (conta_id)
    REFERENCES CONTA (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: CLIENTE_TIPO_CLIENTE (table: CLIENTE)
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_TIPO_CLIENTE
    FOREIGN KEY (tipo_cliente_id)
    REFERENCES TIPO_CLIENTE (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: CONTATO_PESSOA (table: CONTATO)
ALTER TABLE CONTATO ADD CONSTRAINT CONTATO_PESSOA
    FOREIGN KEY (pessoa_id)
    REFERENCES PESSOA (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: CONTA_TIPO_CONTA_CONTA (table: CONTA_TIPO_CONTA)
ALTER TABLE CONTA_TIPO_CONTA ADD CONSTRAINT CONTA_TIPO_CONTA_CONTA
    FOREIGN KEY (CONTA_id)
    REFERENCES CONTA (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: CONTA_TIPO_CONTA_TIPO_CONTA (table: CONTA_TIPO_CONTA)
ALTER TABLE CONTA_TIPO_CONTA ADD CONSTRAINT CONTA_TIPO_CONTA_TIPO_CONTA
    FOREIGN KEY (TIPO_CONTA_id)
    REFERENCES TIPO_CONTA (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: DOCUMENTOS_PESSOA_FISICA (table: DOCUMENTOS)
ALTER TABLE DOCUMENTOS ADD CONSTRAINT DOCUMENTOS_PESSOA_FISICA
    FOREIGN KEY (PESSOA_FISICA_ID)
    REFERENCES PESSOA_FISICA (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: ENDERECO_CONTATO (table: ENDERECO)
ALTER TABLE ENDERECO ADD CONSTRAINT ENDERECO_CONTATO
    FOREIGN KEY (CONTATO_ID)
    REFERENCES CONTATO (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: ENDERECO_MUNICIPIO (table: ENDERECO)
ALTER TABLE ENDERECO ADD CONSTRAINT ENDERECO_MUNICIPIO
    FOREIGN KEY (MUNICIPIO_ID)
    REFERENCES MUNICIPIO (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: ENDERECO_TIPO_LOGRADOURO (table: ENDERECO)
ALTER TABLE ENDERECO ADD CONSTRAINT ENDERECO_TIPO_LOGRADOURO
    FOREIGN KEY (TIPO_LOGRADOURO_ID)
    REFERENCES TIPO_LOGRADOURO (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: GRUPO_POLITICAS (table: GRUPO)
ALTER TABLE GRUPO ADD CONSTRAINT GRUPO_POLITICAS
    FOREIGN KEY (PERFIL_ID)
    REFERENCES PERFIL (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: ITEM_MENU (table: ITEM)
ALTER TABLE ITEM ADD CONSTRAINT ITEM_MENU
    FOREIGN KEY (MENU_ID)
    REFERENCES MENU (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: MENU_MENU (table: MENU)
ALTER TABLE MENU ADD CONSTRAINT MENU_MENU
    FOREIGN KEY (MENU_ID)
    REFERENCES MENU (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: MENU_MODULO (table: MENU)
ALTER TABLE MENU ADD CONSTRAINT MENU_MODULO
    FOREIGN KEY (MODULO_ID)
    REFERENCES MODULO (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: MODULOS_SISTEMAS (table: MODULO)
ALTER TABLE MODULO ADD CONSTRAINT MODULOS_SISTEMAS
    FOREIGN KEY (SISTEMA_ID)
    REFERENCES SISTEMA (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: PAPEL_PAPEL (table: PAPEL)
ALTER TABLE PAPEL ADD CONSTRAINT PAPEL_PAPEL
    FOREIGN KEY (PAPEL_ID)
    REFERENCES PAPEL (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: PERFIL_ITEM_ITEM (table: PERFIL_ITEM)
ALTER TABLE PERFIL_ITEM ADD CONSTRAINT PERFIL_ITEM_ITEM
    FOREIGN KEY (ITEM_ID)
    REFERENCES ITEM (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: PERFIL_ITEM_PERFIL (table: PERFIL_ITEM)
ALTER TABLE PERFIL_ITEM ADD CONSTRAINT PERFIL_ITEM_PERFIL
    FOREIGN KEY (PERFIL_ID)
    REFERENCES PERFIL (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: PERMISSAO_ITEM (table: PERMISSAO_ITEM)
ALTER TABLE PERMISSAO_ITEM ADD CONSTRAINT PERMISSAO_ITEM
    FOREIGN KEY (ITEM_ID)
    REFERENCES ITEM (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: PERMISSAO_SERVICO_PERFIL (table: PERMISSAO_SERVICO)
ALTER TABLE PERMISSAO_SERVICO ADD CONSTRAINT PERMISSAO_SERVICO_PERFIL
    FOREIGN KEY (PERFIL_ID)
    REFERENCES PERFIL (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: PERMISSAO_SERVICO_SERVICO (table: PERMISSAO_SERVICO)
ALTER TABLE PERMISSAO_SERVICO ADD CONSTRAINT PERMISSAO_SERVICO_SERVICO
    FOREIGN KEY (SERVICO_ID)
    REFERENCES SERVICO (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: PESSOA_FISICA_CARGO (table: PESSOA_FISICA)
ALTER TABLE PESSOA_FISICA ADD CONSTRAINT PESSOA_FISICA_CARGO
    FOREIGN KEY (CARGO_ID)
    REFERENCES CARGO (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: PESSOA_FISICA_PAIS (table: PESSOA_FISICA)
ALTER TABLE PESSOA_FISICA ADD CONSTRAINT PESSOA_FISICA_PAIS
    FOREIGN KEY (PAIS_ID)
    REFERENCES PAIS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: PESSOA_FISICA_PESSOA (table: PESSOA_FISICA)
ALTER TABLE PESSOA_FISICA ADD CONSTRAINT PESSOA_FISICA_PESSOA
    FOREIGN KEY (PESSOA_ID)
    REFERENCES PESSOA (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: PESSOA_JURIDICA_PESSOA (table: PESSOA_JURIDICA)
ALTER TABLE PESSOA_JURIDICA ADD CONSTRAINT PESSOA_JURIDICA_PESSOA
    FOREIGN KEY (PESSOA_ID)
    REFERENCES PESSOA (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: PESSOA_PAPEL_PAPEL (table: VINCULO_PAPEL)
ALTER TABLE VINCULO_PAPEL ADD CONSTRAINT PESSOA_PAPEL_PAPEL
    FOREIGN KEY (PAPEL_ID)
    REFERENCES PAPEL (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: PESSOA_PAPEL_VINCULO (table: VINCULO_PAPEL)
ALTER TABLE VINCULO_PAPEL ADD CONSTRAINT PESSOA_PAPEL_VINCULO
    FOREIGN KEY (VINCULO_ID)
    REFERENCES VINCULO (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: PJ_PESSOA (table: PESSOA_JURIDICA)
ALTER TABLE PESSOA_JURIDICA ADD CONSTRAINT PJ_PESSOA
    FOREIGN KEY (PESSOA_JURIDICA_ID)
    REFERENCES PESSOA_JURIDICA (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: RESPONSAVEL_SISTEMA_SISTEMA (table: RESPONSAVEL_SISTEMA)
ALTER TABLE RESPONSAVEL_SISTEMA ADD CONSTRAINT RESPONSAVEL_SISTEMA_SISTEMA
    FOREIGN KEY (SISTEMA_ID)
    REFERENCES SISTEMA (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: RESPONSAVEL_SISTEMA_USUARIO (table: RESPONSAVEL_SISTEMA)
ALTER TABLE RESPONSAVEL_SISTEMA ADD CONSTRAINT RESPONSAVEL_SISTEMA_USUARIO
    FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: SERVICO_SISTEMA (table: SERVICO)
ALTER TABLE SERVICO ADD CONSTRAINT SERVICO_SISTEMA
    FOREIGN KEY (SISTEMA_ID)
    REFERENCES SISTEMA (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: TELEFONE_CONTATO (table: TELEFONE)
ALTER TABLE TELEFONE ADD CONSTRAINT TELEFONE_CONTATO
    FOREIGN KEY (CONTATO_ID)
    REFERENCES CONTATO (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: TRANSACAO_CONTA_CONTA (table: TRANSACAO_CONTA)
ALTER TABLE TRANSACAO_CONTA ADD CONSTRAINT TRANSACAO_CONTA_CONTA
    FOREIGN KEY (conta_id)
    REFERENCES CONTA (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: TRANSACAO_CONTA_TRANSACAO (table: TRANSACAO_CONTA)
ALTER TABLE TRANSACAO_CONTA ADD CONSTRAINT TRANSACAO_CONTA_TRANSACAO
    FOREIGN KEY (transacao_id)
    REFERENCES TRANSACAO (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: TRANSACOES_TIPO_TRANSACOES (table: TRANSACAO)
ALTER TABLE TRANSACAO ADD CONSTRAINT TRANSACOES_TIPO_TRANSACOES
    FOREIGN KEY (tipo_transacoes_id)
    REFERENCES TIPO_TRANSACOES (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: USUARIO_CONTA_CONTA (table: USUARIO_CONTA)
ALTER TABLE USUARIO_CONTA ADD CONSTRAINT USUARIO_CONTA_CONTA
    FOREIGN KEY (conta_id)
    REFERENCES CONTA (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: USUARIO_CONTA_USUARIO (table: USUARIO_CONTA)
ALTER TABLE USUARIO_CONTA ADD CONSTRAINT USUARIO_CONTA_USUARIO
    FOREIGN KEY (usuario_id)
    REFERENCES USUARIO (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: USUARIO_GRUPO (table: USUARIO)
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_GRUPO
    FOREIGN KEY (GRUPO_ID)
    REFERENCES GRUPO (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: USUARIO_PERFIL (table: USUARIO)
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PERFIL
    FOREIGN KEY (PERFIL_ID)
    REFERENCES PERFIL (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: VINCULO_PESSOA (table: VINCULO)
ALTER TABLE VINCULO ADD CONSTRAINT VINCULO_PESSOA
    FOREIGN KEY (PESSOA_ID)
    REFERENCES PESSOA (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: VINCULO_TIPO_CONTA_SERVICO_CONTA_TIPO_CONTA (table: VINCULO_TIPO_CONTA_SERVICO)
ALTER TABLE VINCULO_TIPO_CONTA_SERVICO ADD CONSTRAINT VINCULO_TIPO_CONTA_SERVICO_CONTA_TIPO_CONTA
    FOREIGN KEY (CONTA_TIPO_CONTA_id)
    REFERENCES CONTA_TIPO_CONTA (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: VINCULO_TIPO_CONTA_SERVICO_PRODUTOS_SERVICOS (table: VINCULO_TIPO_CONTA_SERVICO)
ALTER TABLE VINCULO_TIPO_CONTA_SERVICO ADD CONSTRAINT VINCULO_TIPO_CONTA_SERVICO_PRODUTOS_SERVICOS
    FOREIGN KEY (PRODUTOS_SERVICOS_id)
    REFERENCES PRODUTOS_SERVICOS (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: VINCULO_USUARIO (table: VINCULO)
ALTER TABLE VINCULO ADD CONSTRAINT VINCULO_USUARIO
    FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: email_CONTATO (table: EMAIL)
ALTER TABLE EMAIL ADD CONSTRAINT email_CONTATO
    FOREIGN KEY (CONTATO_ID)
    REFERENCES CONTATO (id)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- End of file.

